# Generated by Django 2.1.4 on 2019-05-19 14:57

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('identifier', models.TextField(unique=True, verbose_name='identifier')),
                ('chapter_number', models.IntegerField(null=True, verbose_name='chapter_number')),
                ('verse_number', models.IntegerField(null=True, verbose_name='verse_or_stanza_number')),
                ('line_number', models.IntegerField(null=True, verbose_name='line_or_verseline_number')),
                ('context', models.TextField(verbose_name='Context')),
                ('structure', django.contrib.postgres.fields.jsonb.JSONField()),
                ('display_settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('algorithm_settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('type', models.TextField(verbose_name='Type')),
                ('scope', models.TextField(verbose_name='Scope')),
                ('classification', models.TextField(verbose_name='Class')),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('conditions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exceptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('t', models.TextField(verbose_name='t')),
                ('n', models.TextField(verbose_name='n')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(null=True)),
                ('created_by', models.TextField(blank=True, verbose_name='created_by')),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_by', models.TextField(blank=True, verbose_name='Last_modified_by')),
                ('version_number', models.IntegerField(null=True)),
                ('identifier', models.TextField(unique=True, verbose_name='Identifier')),
                ('name', models.TextField(verbose_name='name')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('basetext', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Transcription')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Collection')),
                ('editors', models.ManyToManyField(blank=True, related_name='projects_as_editor', to=settings.AUTH_USER_MODEL)),
                ('managing_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managing_editor', to=settings.AUTH_USER_MODEL)),
                ('witnesses', models.ManyToManyField(blank=True, related_name='witnesses', to='transcriptions.Transcription')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collation_project', to='transcriptions.Work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_decisions', to='collation.Project'),
        ),
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_collation', to='collation.Project'),
        ),
        migrations.AddField(
            model_name='collation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_collation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collated_verse', to='transcriptions.Work'),
        ),
    ]
