# Generated by Django 2.1.4 on 2019-06-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collation',
            old_name='verse_number',
            new_name='stanza_number',
        ),
    ]
