# Generated by Django 2.2 on 2020-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0003_auto_20200225_1210'),
        ('collation', '0003_auto_20200225_1212'),
    ]

    operations = [
    ]
