# Generated by Django 2.2 on 2021-03-01 23:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0004_merge_20200225_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='basetext',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Transcription'),
        ),
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are absolutely\n                                        sure you know what you are doing.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.TextField(max_length=30, unique=True, verbose_name='Project Identifier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('ae', 'Avestan'), ('gu', 'Gujarati'), ('fa', 'Persian'), ('sa', 'Sanskrit'), ('ae-Avst', 'Avestan in Avesta Script'), ('ae-Phlv', 'Avestan in Pahlavi Script'), ('ae-Gujr', 'Avestan in Gujarati Script'), ('gu-Gujr', 'Gujarati in Gujarati Script'), ('gu-Arab', 'Gujarati in Arabic Script'), ('pal-Avst', 'Zoroastrian Middle Persian in Avesta Script'), ('pal-Phlv', 'Zoroastrian Middle Persian in Pahlavi Script'), ('pal-Phli', 'Middle Persian in inscriptional Pahlavi Script'), ('pal-Gujr', 'Zoroastrian Middle Persian in Gujarati Script'), ('ar', 'Arabic')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Project Name'),
        ),
    ]
