# Generated by Django 2.2 on 2021-04-25 14:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0005_auto_20210301_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ceremonies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='ceremony_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are absolutely\n                                            sure you know what you are doing.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supplement_range',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are absolutely\n                                            sure you know what you are doing.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are absolutely\n                                         sure you know what you are doing.', null=True),
        ),
    ]
