# Generated by Django 3.2 on 2021-10-22 10:10

import collation.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0006_auto_20210425_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collation',
            name='algorithm_settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='collation',
            name='data_settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='collation',
            name='display_settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='collation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collation',
            name='structure',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='decision',
            name='conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceremonies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=collation.models.get_default_ceremonies, help_text='Add all ceremonies in desired display order separated with commas.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceremony_mapping',
            field=models.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are\n                                                  absolutely sure you know what you are doing.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=models.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are\n                                               absolutely sure you know what you are doing.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplement_range',
            field=models.JSONField(blank=True, help_text='This field is in JSON. Do not mess with this unless you are\n                                                  absolutely sure you know what you are doing.', null=True),
        ),
    ]
